version: '3.1'
services: 
    web:
        container_name: nginx
        image: nginx:stable-alpine
        restart: unless-stopped
        volumes:
        - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        - ./files:/workspace
        ports:
        - "8080:80"
